name: Prueba Token Self-hosted

on:
  push:
    branches: [ "*" ]

jobs:
  comprobar-tokens:
    runs-on: self-hosted
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Comparar DEV_TOKEN con LOCAL_DEV_TOKEN
        env:
          SECRET_DEV: ${{ secrets.DEV_TOKEN }}
        run: |
          Write-Host "Comprobando tokens..."
          if ($env:SECRET_DEV -eq $env:LOCAL_DEV_TOKEN) {
            Write-Host "ÉXITO Los tokens coinciden correctamente."
            exit 0
          } else {
            Write-Host "ERROR Los tokens NO coinciden."
            exit 1
          }